version: '3.6'

services:
  database:
    container_name: postgres_database
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test